mcp:
  servers:
    gmail:
      command: "C:\\Users\\User\\.local\\bin\\uv.exe"
      args:
        [
          "--directory",
          "D:/Projects/MCP_Claude/MCP_claude/gmail_mcp",
          "run",
          "gmail_tools.py",
          "--creds-file-path",
          "D:/Projects/MCP_Claude/MCP_claude/gmail_mcp/credentials.json",
          "--token-path",
          "D:/Projects/MCP_Claude/MCP_claude/gmail_mcp/token.json",
        ]
    weather:
      command: "C:\\Users\\User\\.local\\bin\\uv.exe"
      args: ["D:\\Projects\\MCP_Claude\\MCP_claude\\weather\\weather.py"]
      host: "127.0.0.1"
      port: 8000
      timeout: 30000

      # consider defining sensitive values in a separate mcp_agent.secrets.yaml file
      # env:
      #   GMAIL_CLIENT_ID: "your-client-id"
      #   GMAIL_CLIENT_SECRET: "your-client-secret"
      #   GMAIL_REFRESH_TOKEN: "your-refresh-token"
      #   GMAIL_USER_ID: "your-user-id"
    # fetch:
    #   command: "uvx"
    #   args: ["mcp-server-fetch"]
    # filesystem:
    #   command: "npx"
    #   args: ["-y", "@modelcontextprotocol/server-filesystem", "."]
    # slack:
    #   command: "npx"
    #   args: ["-y", "@modelcontextprotocol/server-slack"]
    #   # consider defining sensitive values in a separate mcp_agent.secrets.yaml file
    #   # env:
    #   #   SLACK_BOT_TOKEN: "xoxb-your-bot-token"
    #   #   SLACK_TEAM_ID": "T01234567"
